In [35]:
import pandas as pd
data = pd.read_csv('/home/kali/Downloads/lego-analysis-master/datasets/parent_themes.csv')
for i in range (len(data)):
    old = data['name'].unique()[i]
    data = data.replace({old:i})
data.head(50)

     id  name  is_licensed
0     1     0        False
1    22     1        False
2    50     2        False
3   112     3        False
4   126     4        False
5   147     5        False
6   155     6        False
7   158     7         True
8   186     8        False
9   204     9        False
10  206    10        False
11  233    11        False
12  246    12         True
13  252    13        False
14  254    14        False
15  258    15        False
16  263    16         True
17  264    17         True
18  269    18         True
19  270    19         True
20  271    20         True
21  272    21         True
22  273    22        False
23  275    23         True
24  276    24        False
25  278    25        False
26  279    26        False
27  296    27        False
28  301    28        False
29  302    29        False
30  304    30        False
31  307    31        False
32  315    32        False
33  317    33         True
34  318    34        False
35  324    35        False
36  363    36        False
37  364    37        False
38  365    38        False
39  384    39        False
40  385    40        False
41  386    41        False
42  387    42        False
43  388    43         True
44  389    44        False
45  390    45        False
46  397    46        False
47  398    47        False
48  399    48        False
49  400    49        False

In [44]:
import tensorflow as ten
from tensorflow import keras
import numpy as np


model = keras.Sequential()
model.add(keras.layers.Flatten(input_shape = [1]))
model.add(keras.layers.Dense(10,activation = 'relu'))
model.add(keras.layers.Dense(2,activation = 'sigmoid'))
model.compile(optimizer = 'adam' , metrics = 'accuracy',loss = 'sparse_categorical_crossentropy')
model.fit(data['name'] , data['is_licensed'],epochs = 10)
pred = model.predict(data['name'])

Epoch 1/10
4/4 [==============================] - 0s 1ms/step - loss: 0.9818 - accuracy: 0.7928
Epoch 2/10
4/4 [==============================] - 0s 2ms/step - loss: 0.7038 - accuracy: 0.7928
Epoch 3/10
4/4 [==============================] - 0s 2ms/step - loss: 0.5782 - accuracy: 0.7658
Epoch 4/10
4/4 [==============================] - 0s 1ms/step - loss: 0.6094 - accuracy: 0.7658
Epoch 5/10
4/4 [==============================] - 0s 1ms/step - loss: 0.5611 - accuracy: 0.7838
Epoch 6/10
4/4 [==============================] - 0s 1ms/step - loss: 0.5702 - accuracy: 0.7928
Epoch 7/10
4/4 [==============================] - 0s 2ms/step - loss: 0.5773 - accuracy: 0.8018
Epoch 8/10
4/4 [==============================] - 0s 1ms/step - loss: 0.5667 - accuracy: 0.8018
Epoch 9/10
4/4 [==============================] - 0s 1ms/step - loss: 0.5647 - accuracy: 0.8018
Epoch 10/10
4/4 [==============================] - 0s 1ms/step - loss: 0.5572 - accuracy: 0.8018
4/4 [==============================] - 0s 988us/step

In [55]:
pred = [np.argmax(i) for i in pred]
from collections import Counter
cout = Counter()
count =cout.update(Counter(pred))
count